### ISSUE TITLE
Growl errors

### ISSUE THREAD

**Issue by loveorigami** [infoweb-internet-solutions/yii2-cms-sliders#17]
Thanks for usefull module.
I am find here
https://github.com/infoweb-internet-solutions/yii2-cms-sliders/blob/master/views/images/index.php#L35
```
//it is necessary to see all the errors for all the files. @todo Show growl message
```

For this messages I create yii2-notification-wrapper
https://github.com/loveorigami/yii2-notification-wrapper

Use it very simply. In action you set message as
```
\Yii::$app->getSession()->setFlash('error',   'noty error');
```
That's all!

**Comment by fabiomaggio** [comment]
Thanks @loveorigami !
I will definitely take a look at it
